version: '3.8'
services:
  neo4j:
    image: neo4j:5.7
    container_name: navvv_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import

  notebook:
    build: .
    container_name: navvv_kg_notebook
    ports:
      - "8888:8888"
    depends_on:
      - neo4j

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import: